### PR TITLE
Update robovac.py to include T2190

### PR DESCRIPTION
**Pull request by imhotep**
This works with my [Vacuum L70](https://us.eufy.com/products/t2190121-f). Before that I'd get the ModelNotSupported exception (for good reason).

Wasn't sure if I should have added a new letter under `L` under `ROBOVAC_SERIES` but it works as is and all of the features seem to work.

### CODE REVIEW

**Comment by CodeFoodPixels** [comment]
T2190 is already in the L series list, isn't it?

**Comment by imhotep** [comment]
Yup! I was using version 1.0 on HACS which does´t have it. I am just going to point it to main.

**Comment by imhotep** [comment]
@CodeFoodPixels the ability the set the IP of the vacuum has gone away. How do I set it? By default my entity is unavailable now. If it's autodetecting, it's failing for me.

**Comment by CodeFoodPixels** [comment]
It should be autodiscovering the IP address. Have you got any restrictions on the network?

**Comment by imhotep** [comment]
@CodeFoodPixels I don't have any restrictions. The IP seems correct but it's failing on a specific key:
```
2023-09-04 09:36:18.616 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to eb0cd280189d9f12caawyv (192.168.1.197:6668)
2023-09-04 09:36:20.618 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Retrying send due to error. Failed to send data to eb0cd280189d9f12caawyv (192.168.1.197:6668)
2023-09-04 09:36:20.618 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to eb0cd280189d9f12caawyv (192.168.1.197:6668)
2023-09-04 09:36:21.667 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Retrying send due to error. Connection to eb0cd280189d9f12caawyv (192.168.1.197:6668) failed: [Errno 113] Host is unreachable
2023-09-04 09:36:21.668 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to eb0cd280189d9f12caawyv (192.168.1.197:6668)
2023-09-04 09:36:21.771 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to eb0cd280189d9f12caawyv (192.168.1.197:6668): Message(0xa, {'gwId': 'eb0cd280189d9f12caawyv', 'devId': 'eb0cd280189d9f12caawyv'}, 424403537, <Device eb0cd280189d9f12caawyv (192.168.1.197:6668)>)
2023-09-04 09:36:22.160 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from eb0cd280189d9f12caawyv (192.168.1.197:6668): Message(0xa, {'dps': {'2': False, '5': 'Nosweep', '15': 'completed', '101': True, '102': 'Standard', '103': False, '104': 100, '105': 'MopMiddle', '106': 0, '107': False, '108': '[-372,3861,1530]', '109': 40, '110': 0, '111': 80, '112': 134236, '113': 134236, '114': 134236, '115': 'Sensor', '118': True, '119': 134236, '120': 2101, '122': 'Nosweep', '127': 4328, '129': True, '132': 43, '133': 0, '134': 1}}, 424403537, None)
2023-09-04 09:36:22.162 ERROR (MainThread) [homeassistant.components.vacuum] robovac: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/robovac/vacuum.py", line 323, in async_update
    self.tuyastatus.get(TUYA_CODES["{}_CONSUMABLES".format(robovac_series)])
                        ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 789, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'L_CONSUMABLES'
2023-09-04 09:36:22.171 INFO (MainThread) [custom_components.robovac.tuyalocalapi] Received updated state eb0cd280189d9f12caawyv (192.168.1.197:6668): {'106': 0, '2': False, '5': 'Nosweep', '15': 'completed', '101': True, '102': 'Standard', '103': False, '104': 100, '105': 'MopMiddle', '107': False, '108': '[-372,3861,1530]', '109': 40, '110': 0, '111': 80, '112': 134236, '113': 134236, '114': 134236, '115': 'Sensor', '118': True, '119': 134236, '120': 2101, '122': 'Nosweep', '127': 4328, '129': True, '132': 43, '133': 0, '134': 1}
```

**Comment by CodeFoodPixels** [comment]
I think I fixed this earlier today, redownload from main and give it a try please.

**Comment by CodeFoodPixels** [comment]
Can you give main another try, I think it's resolved?

**Comment by imhotep** [comment]
@CodeFoodPixels looks like that did the trick! However the status of the vacuum is not reporting correctly. It's alternating beteeen error/cleaning/stop etc…nothing in the logs.
Screen Shot 2023-09-06 at 9 24 06 AM

**Comment by imhotep** [comment]
@CodeFoodPixels here's some more logs
```
2023-09-07 18:16:42.232 ERROR (MainThread) [custom_components.robovac.tuyalocalapi] Incomplete read from: eb0cd280189d9f12caawyv (
192.168.1.197:6668) : 0 bytes read on a total of undefined expected bytes
2023-09-07 18:17:02.133 ERROR (MainThread) [custom_components.robovac.tuyalocalapi] Connection to eb0cd280189d9f12caawyv (192.168.1.197:6668) failed: [Errno 32] Broken pipe
```
Not sure if they're related to the status update not reporting correctly

**Comment by CodeFoodPixels** [comment]
Can you have a look at #21, that's where I've been tracking this

**Pull request closed without merging**
