### PR TITLE
Add support for the LR20 (T2192)

### PR DESCRIPTION
**Pull request by LarveyOfficial**

### CODE REVIEW

**Comment by LarveyOfficial** [comment]
Miss-click

**Comment by LarveyOfficial** [comment]
current fan speed status does not work, is just Unknown. The code is a mess, maybe someone else can figure it out

**Comment by LarveyOfficial** [comment]
*You can SET the fan speed, just not see it

**Comment by CodeFoodPixels** [comment]
Added LR20 in f4e4a647ef4ac011a38c42f5c91bc5ecde122dbb, if you have other issues, please raise it as an issue

**Comment by LarveyOfficial** [comment]
The LR20 doesn't have consumables. It's not an L series it's an LR series. If not the console will be flooded with errors.

**Pull request closed without merging**
